spring:
  application:
    name: RATING-SERVICE
  data:
    mongodb:
      uri: mongodb+srv://mongodb:YbVW2z2MHaByLfvj@spring-boot.udvszal.mongodb.net/?retryWrites=true&w=majority
      database: microservices
server:
  port: 8083
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
